config/routes.rb
Rails.application.routes.draw do
  root 'application#index'
  
  get 'hello', to: 'pages#hello'
  get 'goodbye', to: 'pages#goodbye'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def index
    render 'pages/index' 
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def hello
  end

  def goodbye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="content">
</div>
    <footer id="myFooter">
        <div class="container">
            
            </div>
        </div>
        <div class="social-networks">
            <a href="https://twitter.com/SandyVern" class="twitter"><i class="fa fa-twitter"></i></a>
            <a href="https://www.facebook.com/Sandra.E.Hogan" class="facebook"><i class="fa fa-facebook-official"></i></a>
            <a href="https://www.instagram.com/sandyvern" class="instagram"><i class="fa fa-instagram"></i></a>
            <a href="https://github.com/sandyvern" class="github"><i class="fa fa-github"></i></a>
            <a href="https://bitbucket.org/sandyvern" class="bitbucket"><i class="fa fa-bitbucket"></i></a>
            <a href="https://plus.google.com/u/0/+SandyHogan" class="google"><i class="fa fa-google-plus"></i></a>
        </div>
        <div class="footer-copyright">
            <p>© <%= Time.current.year %> Create with <i class="fa fa-heart"></i> by Sandy Hogan - All Rights Reserved </p>
        </div>
    </footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to root_path, class: "navbar-brand" do %>
        <i class="fa fa-globe fa-lg"></i>
          Hello World
      <% end %>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        
      </ul>
      
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloApp</title>
    <%= csrf_meta_tags %>
    
    <%= favicon_link_tag 'favicon/favicon.ico' %>
    
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    
    <div class="container">
      <%= yield %>
    </div>
    
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/goodbye.html.erb
<div class="jumbotron goodbye">
  <h1></h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="well text-center">
      <h2>Goodbye, world!</h2>
      <h2>¡Adiós, mundo!</h2>
      <h2>Au revoir le monde!</h2>
      <h2>Alavida duniya!</h2>
      <h2>Addio mondo!</h2>
      <h2>Auf Wiedersehen Welt!</h2>
    </div>
  </div>
</div>


<div class="text-center">
  <%= link_to 'Hello', hello_path, class: 'btn btn-primary' %> | <%= link_to 'Home', root_path, class: 'btn btn-success' %>
</div>

app/views/pages/hello.html.erb
<div class="jumbotron hello">
  <h1></h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="well text-center">
      <h2>Hello, world!</h2>
      <h2>¡Hola, mundo!</h2>
      <h2>Bonjour le monde!</h2>
      <h2>Namaste duniya</h2>
      <h2>Ciao mondo</h2>
      <h2>Hallo Welt</h2>
    </div>
  </div>
</div>


<div class="text-center">
  <%= link_to 'Goodbye', goodbye_path, class: 'btn btn-primary' %> | <%= link_to 'Home', root_path, class: 'btn btn-success' %>
</div>

app/views/pages/index.html.erb
<div class="jumbotron text-center">
  <h1>Hello World App</h1>
  <%= image_tag("globe-world.png", alt: "Globe View", size: "200x200") %>
  <p>The first application from the <strong>Ruby on Rails Tutorial</strong> by <strong><em>Michael Hartl</em></strong></p>
  
  <div class="links">
    <%= link_to 'Hello', hello_path, class: 'btn btn-primary' %>
    <%= link_to 'Goodbye', goodbye_path, class: 'btn btn-success' %>
    <%= link_to 'Code', "https://github.com/sandyvern/rails-tutorial", class: 'btn btn-info' %>
  </div>
</div>